//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace matsyshenV_ISIT420_HW4
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreTable()
        {
            this.Orders = new HashSet<Order>();
            this.SalesPersonTables = new HashSet<SalesPersonTable>();
        }
    
        public int storeID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int NumberEmployees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesPersonTable> SalesPersonTables { get; set; }
    }
}
